package:
  name: DailyMed-API-Schema
  version: 1.0

source:
  git_url: https://github.com/akirti/dailymed_sracping

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: